2025-04-08 22:02:42,740 - INFO - Flask app started successfully!
2025-04-08 22:02:42,833 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
2025-04-08 22:02:42,833 - INFO - [33mPress CTRL+C to quit[0m
2025-04-08 22:02:42,835 - INFO -  * Restarting with stat
2025-04-08 22:02:43,289 - INFO - Flask app started successfully!
2025-04-08 22:02:43,307 - WARNING -  * Debugger is active!
2025-04-08 22:02:43,330 - INFO -  * Debugger PIN: 370-831-144
2025-04-08 22:03:05,175 - INFO - 127.0.0.1 - - [08/Apr/2025 22:03:05] "GET / HTTP/1.1" 200 -
2025-04-08 22:03:05,406 - INFO - 127.0.0.1 - - [08/Apr/2025 22:03:05] "GET /static/style.css HTTP/1.1" 200 -
2025-04-08 22:08:34,323 - ERROR - Error processing request: HTTPConnectionPool(host='fastapi', port=8000): Max retries exceeded with url: /predict/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001D9687B2B90>: Failed to resolve 'fastapi' ([Errno 11001] getaddrinfo failed)"))
2025-04-08 22:08:34,331 - INFO - 127.0.0.1 - - [08/Apr/2025 22:08:34] "POST / HTTP/1.1" 200 -
2025-04-08 22:08:34,478 - INFO - 127.0.0.1 - - [08/Apr/2025 22:08:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-04-08 22:09:56,452 - ERROR - Error processing request: HTTPConnectionPool(host='fastapi', port=8000): Max retries exceeded with url: /predict/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001D9687B11E0>: Failed to resolve 'fastapi' ([Errno 11001] getaddrinfo failed)"))
2025-04-08 22:09:56,453 - INFO - 127.0.0.1 - - [08/Apr/2025 22:09:56] "POST / HTTP/1.1" 200 -
2025-04-08 22:09:56,490 - INFO - 127.0.0.1 - - [08/Apr/2025 22:09:56] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-04-08 22:15:09,289 - INFO - 127.0.0.1 - - [08/Apr/2025 22:15:09] "GET / HTTP/1.1" 200 -
2025-04-08 22:15:09,483 - INFO - 127.0.0.1 - - [08/Apr/2025 22:15:09] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-04-08 22:15:33,416 - ERROR - Error processing request: HTTPConnectionPool(host='fastapi', port=8000): Max retries exceeded with url: /predict/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001D9687B2590>: Failed to resolve 'fastapi' ([Errno 11001] getaddrinfo failed)"))
2025-04-08 22:15:33,416 - INFO - 127.0.0.1 - - [08/Apr/2025 22:15:33] "POST / HTTP/1.1" 200 -
2025-04-08 22:15:33,477 - INFO - 127.0.0.1 - - [08/Apr/2025 22:15:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
